In [3]:
import pandas as pd

landmarks = pd.read_csv(r'C:\Users\andjelija.jovanovic\Desktop\movement project\data\landmarks.csv')   
labels = pd.read_csv(r'C:\Users\andjelija.jovanovic\Desktop\movement project\data\labels.csv')         


print("LANDMARKS shape:", landmarks.shape)
print("LABELS shape:", labels.shape)

landmarks.head()


LANDMARKS shape: (83922, 101)
LABELS shape: (448, 2)


vid_id  frame_order    x_nose     y_nose    z_nose  x_left_eye_inner  \
0       0            0 -0.645851 -59.992630 -80.98500          0.560464   
1       0            1 -0.290473 -61.069310 -78.47870          0.881309   
2       0            2 -0.378156 -61.102000 -86.33219          0.968603   
3       0            3 -0.004211 -61.846817 -98.94910          1.419466   
4       0            4  0.215262 -59.717796 -96.07627          1.495876   

   y_left_eye_inner  z_left_eye_inner  x_left_eye  y_left_eye  ...  \
0        -62.555250        -76.384210    1.362609  -62.543415  ...   
1        -63.674810        -73.719315    1.639633  -63.648945  ...   
2        -63.431263        -81.922356    1.788657  -63.423435  ...   
3        -64.424550        -94.673550    2.102673  -64.361015  ...   
4        -62.196190        -91.907270    2.157559  -62.149612  ...   

   z_left_heel  x_right_heel  y_right_heel  z_right_heel  x_left_foot_index  \
0    42.493310     -4.885307     67.512770     40.333897           5.356711   
1    48.487360     -4.753275     64.969570     45.439384           5.492989   
2    49.983517     -4.517086     64.510980     48.996880           5.433758   
3    53.762500     -4.674540     64.720245     53.581780           5.768750   
4    53.409090     -4.098778     62.490230     52.845634           5.633003   

   y_left_foot_index  z_left_foot_index  x_right_foot_index  \
0          73.934240          11.780330           -5.852993   
1          73.177270          18.108229           -6.038326   
2          72.199036          19.192911           -5.513490   
3          72.696290          23.325266           -5.238461   
4          70.438194          23.657516           -5.467475   

   y_right_foot_index  z_right_foot_index  
0            73.78203            9.016774  
1            72.70349           14.222010  
2            71.79309           17.322145  
3            72.11217           21.887375  
4            70.08317           22.496626  

[5 rows x 101 columns]

In [4]:
print("Ukupan broj različitih videa u landmarks:", landmarks['vid_id'].nunique())
print("Ukupan broj različitih videa u labels:", labels['vid_id'].nunique())


missing_in_landmarks = set(labels['vid_id']) - set(landmarks['vid_id'])
print("Vid_id koji su u labels a nema ih u landmarks:", missing_in_landmarks)


Ukupan broj različitih videa u landmarks: 448
Ukupan broj različitih videa u labels: 448
Vid_id koji su u labels a nema ih u landmarks: set()


In [5]:
frames_per_video = landmarks.groupby('vid_id')['frame_order'].nunique()

print("Min broj frame-ova:", frames_per_video.min())
print("Max broj frame-ova:", frames_per_video.max())
print("Srednja vrednost:", frames_per_video.mean())
print("Medijana:", frames_per_video.median())

frames_per_video.describe()


Min broj frame-ova: 14
Max broj frame-ova: 301
Srednja vrednost: 187.32589285714286
Medijana: 185.5


count    448.000000
mean     187.325893
std       77.190233
min       14.000000
25%      123.000000
50%      185.500000
75%      255.000000
max      301.000000
Name: frame_order, dtype: float64

In [6]:
data = landmarks.merge(labels, on='vid_id')
data.head()


vid_id  frame_order    x_nose     y_nose    z_nose  x_left_eye_inner  \
0       0            0 -0.645851 -59.992630 -80.98500          0.560464   
1       0            1 -0.290473 -61.069310 -78.47870          0.881309   
2       0            2 -0.378156 -61.102000 -86.33219          0.968603   
3       0            3 -0.004211 -61.846817 -98.94910          1.419466   
4       0            4  0.215262 -59.717796 -96.07627          1.495876   

   y_left_eye_inner  z_left_eye_inner  x_left_eye  y_left_eye  ...  \
0        -62.555250        -76.384210    1.362609  -62.543415  ...   
1        -63.674810        -73.719315    1.639633  -63.648945  ...   
2        -63.431263        -81.922356    1.788657  -63.423435  ...   
3        -64.424550        -94.673550    2.102673  -64.361015  ...   
4        -62.196190        -91.907270    2.157559  -62.149612  ...   

   x_right_heel  y_right_heel  z_right_heel  x_left_foot_index  \
0     -4.885307     67.512770     40.333897           5.356711   
1     -4.753275     64.969570     45.439384           5.492989   
2     -4.517086     64.510980     48.996880           5.433758   
3     -4.674540     64.720245     53.581780           5.768750   
4     -4.098778     62.490230     52.845634           5.633003   

   y_left_foot_index  z_left_foot_index  x_right_foot_index  \
0          73.934240          11.780330           -5.852993   
1          73.177270          18.108229           -6.038326   
2          72.199036          19.192911           -5.513490   
3          72.696290          23.325266           -5.238461   
4          70.438194          23.657516           -5.467475   

   y_right_foot_index  z_right_foot_index         class  
0            73.78203            9.016774  jumping_jack  
1            72.70349           14.222010  jumping_jack  
2            71.79309           17.322145  jumping_jack  
3            72.11217           21.887375  jumping_jack  
4            70.08317           22.496626  jumping_jack  

[5 rows x 102 columns]

In [7]:
example_vid = data['vid_id'].iloc[0]
example_class = labels[labels['vid_id'] == example_vid]['class'].iloc[0]
print("Primer video ID:", example_vid, "klasa:", example_class)

example_df = data[data['vid_id'] == example_vid].sort_values('frame_order')
example_df.head()


Primer video ID: 0 klasa: jumping_jack


vid_id  frame_order    x_nose     y_nose    z_nose  x_left_eye_inner  \
0       0            0 -0.645851 -59.992630 -80.98500          0.560464   
1       0            1 -0.290473 -61.069310 -78.47870          0.881309   
2       0            2 -0.378156 -61.102000 -86.33219          0.968603   
3       0            3 -0.004211 -61.846817 -98.94910          1.419466   
4       0            4  0.215262 -59.717796 -96.07627          1.495876   

   y_left_eye_inner  z_left_eye_inner  x_left_eye  y_left_eye  ...  \
0        -62.555250        -76.384210    1.362609  -62.543415  ...   
1        -63.674810        -73.719315    1.639633  -63.648945  ...   
2        -63.431263        -81.922356    1.788657  -63.423435  ...   
3        -64.424550        -94.673550    2.102673  -64.361015  ...   
4        -62.196190        -91.907270    2.157559  -62.149612  ...   

   x_right_heel  y_right_heel  z_right_heel  x_left_foot_index  \
0     -4.885307     67.512770     40.333897           5.356711   
1     -4.753275     64.969570     45.439384           5.492989   
2     -4.517086     64.510980     48.996880           5.433758   
3     -4.674540     64.720245     53.581780           5.768750   
4     -4.098778     62.490230     52.845634           5.633003   

   y_left_foot_index  z_left_foot_index  x_right_foot_index  \
0          73.934240          11.780330           -5.852993   
1          73.177270          18.108229           -6.038326   
2          72.199036          19.192911           -5.513490   
3          72.696290          23.325266           -5.238461   
4          70.438194          23.657516           -5.467475   

   y_right_foot_index  z_right_foot_index         class  
0            73.78203            9.016774  jumping_jack  
1            72.70349           14.222010  jumping_jack  
2            71.79309           17.322145  jumping_jack  
3            72.11217           21.887375  jumping_jack  
4            70.08317           22.496626  jumping_jack  

[5 rows x 102 columns]

In [9]:
len(example_df)
landmarks.columns[:40]  



Index(['vid_id', 'frame_order', 'x_nose', 'y_nose', 'z_nose',
       'x_left_eye_inner', 'y_left_eye_inner', 'z_left_eye_inner',
       'x_left_eye', 'y_left_eye', 'z_left_eye', 'x_left_eye_outer',
       'y_left_eye_outer', 'z_left_eye_outer', 'x_right_eye_inner',
       'y_right_eye_inner', 'z_right_eye_inner', 'x_right_eye', 'y_right_eye',
       'z_right_eye', 'x_right_eye_outer', 'y_right_eye_outer',
       'z_right_eye_outer', 'x_left_ear', 'y_left_ear', 'z_left_ear',
       'x_right_ear', 'y_right_ear', 'z_right_ear', 'x_mouth_left',
       'y_mouth_left', 'z_mouth_left', 'x_mouth_right', 'y_mouth_right',
       'z_mouth_right', 'x_left_shoulder', 'y_left_shoulder',
       'z_left_shoulder', 'x_right_shoulder', 'y_right_shoulder'],
      dtype='object')

In [10]:
landmarks.isna().sum().sort_values(ascending=False).head(20)


vid_id               0
frame_order          0
x_nose               0
y_nose               0
z_nose               0
x_left_eye_inner     0
y_left_eye_inner     0
z_left_eye_inner     0
x_left_eye           0
y_left_eye           0
z_left_eye           0
x_left_eye_outer     0
y_left_eye_outer     0
z_left_eye_outer     0
x_right_eye_inner    0
y_right_eye_inner    0
z_right_eye_inner    0
x_right_eye          0
y_right_eye          0
z_right_eye          0
dtype: int64

In [11]:

feature_cols = [c for c in data.columns 
                if c not in ['vid_id', 'frame_order', 'class']]

len(feature_cols), feature_cols[:10]


(99,
 ['x_nose',
  'y_nose',
  'z_nose',
  'x_left_eye_inner',
  'y_left_eye_inner',
  'z_left_eye_inner',
  'x_left_eye',
  'y_left_eye',
  'z_left_eye',
  'x_left_eye_outer'])

In [ ]:
videos = []        
video_labels = []  

for vid, group in data.groupby('vid_id'):
    group = group.sort_values('frame_order')

    seq = group[feature_cols].values.astype('float32')  
    label = group['class'].iloc[0]

    videos.append(seq)
    video_labels.append(label)

len(videos), len(video_labels)


(448, 448)

In [13]:
videos[0].shape, video_labels[0]


((265, 99), 'jumping_jack')

In [14]:
from sklearn.model_selection import train_test_split

X_train_list, X_temp_list, y_train, y_temp = train_test_split(
    videos,
    video_labels,
    test_size=0.3,
    random_state=42,
    stratify=video_labels
)

X_val_list, X_test_list, y_val, y_test = train_test_split(
    X_temp_list,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

len(X_train_list), len(X_val_list), len(X_test_list)


(313, 67, 68)

In [15]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

le = LabelEncoder()
y_train_enc = to_categorical(le.fit_transform(y_train))
y_val_enc   = to_categorical(le.transform(y_val))
y_test_enc  = to_categorical(le.transform(y_test))

num_classes = y_train_enc.shape[1]
num_classes, le.classes_


(5,
 array(['jumping_jack', 'pull_up', 'push_up', 'situp', 'squat'],
       dtype='<U12'))

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = max(seq.shape[0] for seq in X_train_list)
num_features = X_train_list[0].shape[1]
max_len, num_features


(301, 99)

In [17]:
def pad_list(seqs):
    return pad_sequences(
        seqs,
        maxlen=max_len,
        dtype='float32',
        padding='post',
        truncating='post',
        value=0.0
    )

X_train = pad_list(X_train_list)
X_val   = pad_list(X_val_list)
X_test  = pad_list(X_test_list)

X_train.shape, X_val.shape, X_test.shape


((313, 301, 99), (67, 301, 99), (68, 301, 99))

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Masking, LSTM, Bidirectional, Dense, Dropout

model = Sequential([
    Input(shape=(max_len, num_features)),
    Masking(mask_value=0.0),
    Bidirectional(LSTM(64, return_sequences=False)),
    Dropout(0.3),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(num_classes, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ masking_1 (Masking)             │ (None, 301, 99)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 128)            │        83,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 5)              │           325 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 92,549 (361.52 KB)

 Trainable params: 92,549 (361.52 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

checkpoint_path = "best_lstm_model.keras"

callbacks = [
    EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    ),
    ModelCheckpoint(
        filepath=checkpoint_path,
        monitor="val_loss",
        save_best_only=True
    )
]


In [20]:
history = model.fit(
    X_train, y_train_enc,
    epochs=30,
    batch_size=8,
    validation_data=(X_val, y_val_enc),
    callbacks=callbacks,
    verbose=1
)


Epoch 1/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - accuracy: 0.3706 - loss: 1.5171 - val_accuracy: 0.6567 - val_loss: 1.1406
Epoch 2/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - accuracy: 0.6006 - loss: 1.1115 - val_accuracy: 0.7015 - val_loss: 0.8539
Epoch 3/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.7380 - loss: 0.8154 - val_accuracy: 0.6866 - val_loss: 0.7895
Epoch 4/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 84ms/step - accuracy: 0.7732 - loss: 0.6812 - val_accuracy: 0.7015 - val_loss: 0.7357
Epoch 5/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 73ms/step - accuracy: 0.7859 - loss: 0.6076 - val_accuracy: 0.7463 - val_loss: 0.7054
Epoch 6/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 87ms/step - accuracy: 0.7923 - loss: 0.5780 - val_accuracy: 0.7015 - val_loss: 0.6916
Epoch 7/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 72ms/step - accuracy: 0.8403 - loss: 0.4852 - val_accuracy: 0.7313 - val_loss: 0.6769
Epoch 8/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 5s 69ms/step - accuracy: 0.8658 - loss: 0.4336 - val_accuracy: 0.7164 - v

In [21]:
test_loss, test_acc = model.evaluate(X_test, y_test_enc, verbose=1)
print(f"Test accuracy: {test_acc:.3f}, test loss: {test_loss:.3f}")


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8382 - loss: 0.5200
Test accuracy: 0.838, test loss: 0.520


In [22]:
model.save("exercise_lstm_final.keras")

import pickle
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)


In [23]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np


y_test_pred_probs = model.predict(X_test)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)
y_test_true = np.argmax(y_test_enc, axis=1)

cm = confusion_matrix(y_test_true, y_test_pred)
print("Confusion matrix:\n", cm)

print("\nKlasifikacioni izveštaj:\n")
print(classification_report(y_test_true, y_test_pred, target_names=le.classes_))


3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 183ms/step
Confusion matrix:
 [[16  0  0  0  0]
 [ 1 13  1  0  0]
 [ 0  0 14  1  0]
 [ 0  1  0 11  0]
 [ 0  5  1  1  3]]

Klasifikacioni izveštaj:

              precision    recall  f1-score   support

jumping_jack       0.94      1.00      0.97        16
     pull_up       0.68      0.87      0.76        15
     push_up       0.88      0.93      0.90        15
       situp       0.85      0.92      0.88        12
       squat       1.00      0.30      0.46        10

    accuracy                           0.84        68
   macro avg       0.87      0.80      0.80        68
weighted avg       0.86      0.84      0.82        68



In [ ]:
def predict_sequence(seq_2d):
    """
    seq_2d: np.array oblika [num_frames, num_features]
    vraća: (naziv_klase, verovatnoća)
    """
 
    seq_list = [seq_2d.astype('float32')]

    seq_padded = tf.keras.preprocessing.sequence.pad_sequences(
        seq_list,
        maxlen=max_len,
        dtype='float32',
        padding='post',
        truncating='post',
        value=0.0
    )

    probs = model.predict(seq_padded)[0]  # [num_classes]
    class_idx = np.argmax(probs)
    class_name = le.inverse_transform([class_idx])[0]
    confidence = float(probs[class_idx])

    return class_name, confidence


In [25]:

test_seq = X_test_list[0]   
true_label = y_test[0]

pred_label, conf = predict_sequence(test_seq)

print("STVARNA klasa:", true_label)
print("PREDIKCIJA:", pred_label, f"({conf*100:.1f}%)")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
STVARNA klasa: push_up
PREDIKCIJA: situp (86.3%)
